// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {binding} from '../models';
import {models} from '../models';

export function CreatePeriod(arg1:string,arg2:binding.CreatePeriodInput):Promise<models.AvailablePeriod>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<models.AvailablePeriodTag>;

export function DeletePeriod(arg1:string,arg2:string):Promise<void>;

export function DeleteTag(arg1:string,arg2:string):Promise<void>;

export function ForceCloseExpired():Promise<number>;

export function GetActivePeriod():Promise<models.AvailablePeriod>;

export function GetPeriod(arg1:string):Promise<models.AvailablePeriod>;

export function ListPeriods():Promise<Array<models.AvailablePeriod>>;

export function ListTags():Promise<Array<models.AvailablePeriodTag>>;

export function UpdatePeriod(arg1:string,arg2:string,arg3:binding.UpdatePeriodInput):Promise<models.AvailablePeriod>;

export function UpdateTag(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.AvailablePeriodTag>;
