// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePeriod(arg1, arg2) {
  return window['go']['binding']['AvailablePeriodBinding']['CreatePeriod'](arg1, arg2);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['binding']['AvailablePeriodBinding']['CreateTag'](arg1, arg2, arg3);
}

export function DeletePeriod(arg1, arg2) {
  return window['go']['binding']['AvailablePeriodBinding']['DeletePeriod'](arg1, arg2);
}

export function DeleteTag(arg1, arg2) {
  return window['go']['binding']['AvailablePeriodBinding']['DeleteTag'](arg1, arg2);
}

export function ForceCloseExpired() {
  return window['go']['binding']['AvailablePeriodBinding']['ForceCloseExpired']();
}

export function GetActivePeriod() {
  return window['go']['binding']['AvailablePeriodBinding']['GetActivePeriod']();
}

export function GetPeriod(arg1) {
  return window['go']['binding']['AvailablePeriodBinding']['GetPeriod'](arg1);
}

export function ListPeriods() {
  return window['go']['binding']['AvailablePeriodBinding']['ListPeriods']();
}

export function ListTags() {
  return window['go']['binding']['AvailablePeriodBinding']['ListTags']();
}

export function UpdatePeriod(arg1, arg2, arg3) {
  return window['go']['binding']['AvailablePeriodBinding']['UpdatePeriod'](arg1, arg2, arg3);
}

export function UpdateTag(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['AvailablePeriodBinding']['UpdateTag'](arg1, arg2, arg3, arg4);
}
