// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AreaAccessMode(arg1, arg2) {
  return window['go']['binding']['CheckoutBinding']['AreaAccessMode'](arg1, arg2);
}

export function Checkout(arg1, arg2, arg3) {
  return window['go']['binding']['CheckoutBinding']['Checkout'](arg1, arg2, arg3);
}

export function ForceReturn(arg1, arg2) {
  return window['go']['binding']['CheckoutBinding']['ForceReturn'](arg1, arg2);
}

export function GetActiveCheckout(arg1) {
  return window['go']['binding']['CheckoutBinding']['GetActiveCheckout'](arg1);
}

export function GetCheckout(arg1) {
  return window['go']['binding']['CheckoutBinding']['GetCheckout'](arg1);
}

export function Invite(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['CheckoutBinding']['Invite'](arg1, arg2, arg3, arg4);
}

export function ListAccessibleAreas(arg1) {
  return window['go']['binding']['CheckoutBinding']['ListAccessibleAreas'](arg1);
}

export function ListAllCheckouts() {
  return window['go']['binding']['CheckoutBinding']['ListAllCheckouts']();
}

export function ListCheckouts(arg1) {
  return window['go']['binding']['CheckoutBinding']['ListCheckouts'](arg1);
}

export function ListInvitations(arg1) {
  return window['go']['binding']['CheckoutBinding']['ListInvitations'](arg1);
}

export function PlaceAccessMode(arg1, arg2) {
  return window['go']['binding']['CheckoutBinding']['PlaceAccessMode'](arg1, arg2);
}

export function ReassignPersonInCharge(arg1, arg2, arg3) {
  return window['go']['binding']['CheckoutBinding']['ReassignPersonInCharge'](arg1, arg2, arg3);
}

export function Return(arg1, arg2) {
  return window['go']['binding']['CheckoutBinding']['Return'](arg1, arg2);
}

export function RevokeInvite(arg1, arg2) {
  return window['go']['binding']['CheckoutBinding']['RevokeInvite'](arg1, arg2);
}
