// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {service} from '../models';

export function AreaAccessMode(arg1:string,arg2:string):Promise<string>;

export function Checkout(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Checkout>;

export function ForceReturn(arg1:string,arg2:string):Promise<void>;

export function GetActiveCheckout(arg1:string):Promise<models.Checkout>;

export function GetCheckout(arg1:string):Promise<models.Checkout>;

export function Invite(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.CheckoutInvitation>;

export function ListAccessibleAreas(arg1:string):Promise<Array<service.AccessibleArea>>;

export function ListCheckouts(arg1:string):Promise<Array<models.Checkout>>;

export function ListInvitations(arg1:string):Promise<Array<models.CheckoutInvitation>>;

export function PlaceAccessMode(arg1:string,arg2:string):Promise<string>;

export function ReassignOwner(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Return(arg1:string,arg2:string):Promise<void>;

export function RevokeInvite(arg1:string,arg2:string):Promise<void>;
