// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetCurrentActor():Promise<string>;

export function GetRealDID():Promise<string>;

export function IsDevMode():Promise<boolean>;

export function ListAvailableIdentities():Promise<Array<models.User>>;

export function SetCurrentActor(arg1:string):Promise<void>;
