// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentActor() {
  return window['go']['binding']['IdentityBinding']['GetCurrentActor']();
}

export function GetRealDID() {
  return window['go']['binding']['IdentityBinding']['GetRealDID']();
}

export function IsDevMode() {
  return window['go']['binding']['IdentityBinding']['IsDevMode']();
}

export function ListAvailableIdentities() {
  return window['go']['binding']['IdentityBinding']['ListAvailableIdentities']();
}

export function SetCurrentActor(arg1) {
  return window['go']['binding']['IdentityBinding']['SetCurrentActor'](arg1);
}
