// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPolygonsForRegion(arg1) {
  return window['go']['binding']['MapBinding']['GetPolygonsForRegion'](arg1);
}

export function SavePolygon(arg1, arg2) {
  return window['go']['binding']['MapBinding']['SavePolygon'](arg1, arg2);
}
