// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetworkJSON() {
  return window['go']['binding']['MapBinding']['GetNetworkJSON']();
}

export function SaveNetworkJSON(arg1) {
  return window['go']['binding']['MapBinding']['SaveNetworkJSON'](arg1);
}
