// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchWrite(arg1:string):Promise<void>;

export function DeleteDraft(arg1:string):Promise<void>;

export function GetDraftsJSON():Promise<string>;

export function GetGroupsJSON():Promise<string>;

export function GetPolygonsJSON():Promise<string>;

export function SaveDraft(arg1:string):Promise<void>;
