// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchWrite(arg1) {
  return window['go']['binding']['MapBinding']['BatchWrite'](arg1);
}

export function DeleteDraft(arg1) {
  return window['go']['binding']['MapBinding']['DeleteDraft'](arg1);
}

export function GetDraftsJSON() {
  return window['go']['binding']['MapBinding']['GetDraftsJSON']();
}

export function GetGroupsJSON() {
  return window['go']['binding']['MapBinding']['GetGroupsJSON']();
}

export function GetPolygonsJSON() {
  return window['go']['binding']['MapBinding']['GetPolygonsJSON']();
}

export function SaveDraft(arg1) {
  return window['go']['binding']['MapBinding']['SaveDraft'](arg1);
}
