// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNetworkJSON():Promise<string>;

export function SaveNetworkJSON(arg1:string):Promise<void>;
