// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeletePlace(arg1:string):Promise<void>;

export function GetPlace(arg1:string):Promise<models.Place>;

export function ListDeletedPlacesNear(arg1:number,arg2:number,arg3:number):Promise<Array<models.Place>>;

export function ListPlaces(arg1:string):Promise<Array<models.Place>>;

export function SavePlace(arg1:models.Place):Promise<models.Place>;
