// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePlace(arg1) {
  return window['go']['binding']['PlaceBinding']['DeletePlace'](arg1);
}

export function GetPlace(arg1) {
  return window['go']['binding']['PlaceBinding']['GetPlace'](arg1);
}

export function ListDeletedPlacesNear(arg1, arg2, arg3) {
  return window['go']['binding']['PlaceBinding']['ListDeletedPlacesNear'](arg1, arg2, arg3);
}

export function ListPlaces(arg1) {
  return window['go']['binding']['PlaceBinding']['ListPlaces'](arg1);
}

export function SavePlace(arg1) {
  return window['go']['binding']['PlaceBinding']['SavePlace'](arg1);
}
