// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAreaDisplayLabel(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['RegionBinding']['GetAreaDisplayLabel'](arg1, arg2, arg3, arg4);
}

export function ListRegions() {
  return window['go']['binding']['RegionBinding']['ListRegions']();
}
