// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteArea(arg1:string):Promise<void>;

export function DeleteParentArea(arg1:string):Promise<void>;

export function DeleteRegion(arg1:string):Promise<void>;

export function GetArea(arg1:string):Promise<models.Area>;

export function GetAreaDisplayLabel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetParentArea(arg1:string):Promise<models.ParentArea>;

export function GetRegion(arg1:string):Promise<models.Region>;

export function ListAreas(arg1:string):Promise<Array<models.Area>>;

export function ListParentAreas(arg1:string):Promise<Array<models.ParentArea>>;

export function ListRegions():Promise<Array<models.Region>>;

export function RestoreArea(arg1:string):Promise<void>;

export function RestoreParentArea(arg1:string):Promise<void>;

export function RestoreRegion(arg1:string):Promise<void>;

export function SaveArea(arg1:models.Area):Promise<void>;

export function SaveParentArea(arg1:models.ParentArea):Promise<void>;

export function SaveRegion(arg1:models.Region):Promise<void>;
