// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetAreaDisplayLabel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ListRegions():Promise<Array<domain.Region>>;
