// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindPolygonToArea(arg1, arg2) {
  return window['go']['binding']['RegionBinding']['BindPolygonToArea'](arg1, arg2);
}

export function DeleteArea(arg1) {
  return window['go']['binding']['RegionBinding']['DeleteArea'](arg1);
}

export function DeleteParentArea(arg1) {
  return window['go']['binding']['RegionBinding']['DeleteParentArea'](arg1);
}

export function DeleteRegion(arg1) {
  return window['go']['binding']['RegionBinding']['DeleteRegion'](arg1);
}

export function GetArea(arg1) {
  return window['go']['binding']['RegionBinding']['GetArea'](arg1);
}

export function GetAreaDisplayLabel(arg1, arg2, arg3, arg4) {
  return window['go']['binding']['RegionBinding']['GetAreaDisplayLabel'](arg1, arg2, arg3, arg4);
}

export function GetParentArea(arg1) {
  return window['go']['binding']['RegionBinding']['GetParentArea'](arg1);
}

export function GetRegion(arg1) {
  return window['go']['binding']['RegionBinding']['GetRegion'](arg1);
}

export function ListAreas(arg1) {
  return window['go']['binding']['RegionBinding']['ListAreas'](arg1);
}

export function ListParentAreas(arg1) {
  return window['go']['binding']['RegionBinding']['ListParentAreas'](arg1);
}

export function ListRegions() {
  return window['go']['binding']['RegionBinding']['ListRegions']();
}

export function RemapPolygonIds(arg1) {
  return window['go']['binding']['RegionBinding']['RemapPolygonIds'](arg1);
}

export function ReorderRegions(arg1) {
  return window['go']['binding']['RegionBinding']['ReorderRegions'](arg1);
}

export function RestoreArea(arg1) {
  return window['go']['binding']['RegionBinding']['RestoreArea'](arg1);
}

export function RestoreParentArea(arg1) {
  return window['go']['binding']['RegionBinding']['RestoreParentArea'](arg1);
}

export function RestoreRegion(arg1) {
  return window['go']['binding']['RegionBinding']['RestoreRegion'](arg1);
}

export function SaveArea(arg1) {
  return window['go']['binding']['RegionBinding']['SaveArea'](arg1);
}

export function SaveParentArea(arg1) {
  return window['go']['binding']['RegionBinding']['SaveParentArea'](arg1);
}

export function SaveRegion(arg1) {
  return window['go']['binding']['RegionBinding']['SaveRegion'](arg1);
}

export function UnbindPolygonFromArea(arg1) {
  return window['go']['binding']['RegionBinding']['UnbindPolygonFromArea'](arg1);
}

export function UpdateRegion(arg1, arg2, arg3) {
  return window['go']['binding']['RegionBinding']['UpdateRegion'](arg1, arg2, arg3);
}
