// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveSchedulePeriod(arg1, arg2) {
  return window['go']['binding']['ScheduleBinding']['ApproveSchedulePeriod'](arg1, arg2);
}

export function CreateAreaAvailability(arg1) {
  return window['go']['binding']['ScheduleBinding']['CreateAreaAvailability'](arg1);
}

export function CreateSchedulePeriod(arg1) {
  return window['go']['binding']['ScheduleBinding']['CreateSchedulePeriod'](arg1);
}

export function CreateScope(arg1) {
  return window['go']['binding']['ScheduleBinding']['CreateScope'](arg1);
}

export function CreateScopesFromGroups(arg1, arg2) {
  return window['go']['binding']['ScheduleBinding']['CreateScopesFromGroups'](arg1, arg2);
}

export function DeleteAreaAvailability(arg1) {
  return window['go']['binding']['ScheduleBinding']['DeleteAreaAvailability'](arg1);
}

export function DeleteSchedulePeriod(arg1) {
  return window['go']['binding']['ScheduleBinding']['DeleteSchedulePeriod'](arg1);
}

export function DeleteScope(arg1) {
  return window['go']['binding']['ScheduleBinding']['DeleteScope'](arg1);
}

export function GetSchedulePeriod(arg1) {
  return window['go']['binding']['ScheduleBinding']['GetSchedulePeriod'](arg1);
}

export function GetScope(arg1) {
  return window['go']['binding']['ScheduleBinding']['GetScope'](arg1);
}

export function GetSelfID() {
  return window['go']['binding']['ScheduleBinding']['GetSelfID']();
}

export function ListAreaAvailabilities(arg1) {
  return window['go']['binding']['ScheduleBinding']['ListAreaAvailabilities'](arg1);
}

export function ListSchedulePeriods() {
  return window['go']['binding']['ScheduleBinding']['ListSchedulePeriods']();
}

export function ListScopes(arg1) {
  return window['go']['binding']['ScheduleBinding']['ListScopes'](arg1);
}

export function RevokeSchedulePeriodApproval(arg1, arg2) {
  return window['go']['binding']['ScheduleBinding']['RevokeSchedulePeriodApproval'](arg1, arg2);
}

export function UpdateAreaAvailability(arg1) {
  return window['go']['binding']['ScheduleBinding']['UpdateAreaAvailability'](arg1);
}

export function UpdateSchedulePeriod(arg1) {
  return window['go']['binding']['ScheduleBinding']['UpdateSchedulePeriod'](arg1);
}

export function UpdateScope(arg1) {
  return window['go']['binding']['ScheduleBinding']['UpdateScope'](arg1);
}
