// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ApproveSchedulePeriod(arg1:string,arg2:string):Promise<void>;

export function CreateAreaAvailability(arg1:models.AreaAvailability):Promise<void>;

export function CreateSchedulePeriod(arg1:models.SchedulePeriod):Promise<void>;

export function CreateScope(arg1:models.Scope):Promise<void>;

export function CreateScopesFromGroups(arg1:string,arg2:Array<string>):Promise<Array<models.Scope>>;

export function DeleteAreaAvailability(arg1:string):Promise<void>;

export function DeleteSchedulePeriod(arg1:string):Promise<void>;

export function DeleteScope(arg1:string):Promise<void>;

export function GetSchedulePeriod(arg1:string):Promise<models.SchedulePeriod>;

export function GetScope(arg1:string):Promise<models.Scope>;

export function ListAreaAvailabilities(arg1:string):Promise<Array<models.AreaAvailability>>;

export function ListSchedulePeriods():Promise<Array<models.SchedulePeriod>>;

export function ListScopes(arg1:string):Promise<Array<models.Scope>>;

export function RevokeSchedulePeriodApproval(arg1:string,arg2:string):Promise<void>;

export function UpdateAreaAvailability(arg1:models.AreaAvailability):Promise<void>;

export function UpdateSchedulePeriod(arg1:models.SchedulePeriod):Promise<void>;

export function UpdateScope(arg1:models.Scope):Promise<void>;
