// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHiddenTipKeys():Promise<Array<string>>;

export function GetLocale():Promise<string>;

export function ResetHiddenTips():Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetTipHidden(arg1:string,arg2:boolean):Promise<void>;
