// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAreaDetailRadiusKm() {
  return window['go']['binding']['SettingsBinding']['GetAreaDetailRadiusKm']();
}

export function GetHiddenTipKeys() {
  return window['go']['binding']['SettingsBinding']['GetHiddenTipKeys']();
}

export function GetLocale() {
  return window['go']['binding']['SettingsBinding']['GetLocale']();
}

export function ResetHiddenTips() {
  return window['go']['binding']['SettingsBinding']['ResetHiddenTips']();
}

export function SetAreaDetailRadiusKm(arg1) {
  return window['go']['binding']['SettingsBinding']['SetAreaDetailRadiusKm'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['binding']['SettingsBinding']['SetLocale'](arg1);
}

export function SetTipHidden(arg1, arg2) {
  return window['go']['binding']['SettingsBinding']['SetTipHidden'](arg1, arg2);
}
