// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTag(arg1) {
  return window['go']['binding']['UserBinding']['DeleteTag'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['binding']['UserBinding']['DeleteUser'](arg1);
}

export function GetUser(arg1) {
  return window['go']['binding']['UserBinding']['GetUser'](arg1);
}

export function ListInvitations(arg1) {
  return window['go']['binding']['UserBinding']['ListInvitations'](arg1);
}

export function ListTags() {
  return window['go']['binding']['UserBinding']['ListTags']();
}

export function ListUsers() {
  return window['go']['binding']['UserBinding']['ListUsers']();
}

export function SaveInvitation(arg1) {
  return window['go']['binding']['UserBinding']['SaveInvitation'](arg1);
}

export function SaveTag(arg1) {
  return window['go']['binding']['UserBinding']['SaveTag'](arg1);
}

export function SaveUser(arg1) {
  return window['go']['binding']['UserBinding']['SaveUser'](arg1);
}
