// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetGroup(arg1:string):Promise<models.Group>;

export function GetUser(arg1:string):Promise<models.User>;

export function ListGroups():Promise<Array<models.Group>>;

export function ListInvitations(arg1:string):Promise<Array<models.Invitation>>;

export function ListTags():Promise<Array<models.Tag>>;

export function ListUsers():Promise<Array<models.User>>;

export function SaveGroup(arg1:models.Group):Promise<void>;

export function SaveInvitation(arg1:models.Invitation):Promise<void>;

export function SaveTag(arg1:models.Tag):Promise<void>;

export function SaveUser(arg1:models.User):Promise<void>;
