// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {models} from '../models';

export function DeleteVisitRecord(arg1:string):Promise<void>;

export function GetLastMetDate(arg1:string):Promise<time.Time>;

export function ListMyVisitHistory(arg1:string,arg2:string):Promise<Array<models.VisitRecord>>;

export function ListVisitRecords(arg1:string):Promise<Array<models.VisitRecord>>;

export function RecordVisit(arg1:string,arg2:string,arg3:string,arg4:models.VisitResult,arg5:time.Time,arg6:string):Promise<models.VisitRecord>;
